# Clever solution found from:
# https://serverfault.com/a/649355
- include_vars: "{{ item }}"
  with_first_found:
    - "roles/fstab/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "roles/fstab/vars/{{ ansible_distribution }}.yml"
    - "roles/fstab/vars/{{ ansible_os_family }}.yml"
    - "roles/fstab/vars/default-packages.yml"

- name: Install LVM
  become: true
  package:
    name:
      - "{{ lvm_package }}"
    update_cache: true
    state: present

- name: Add logical volumes to fstab
  become: true
  mount:
    src: "/dev/mapper/ValfurSSD-{{ item.name }}"
    path: "{{ item.path }}"
    fstype: ext4
    opts: defaults
    passno: 2
    state: present
  with_items:
    - name: data
      path: /data
    - name: docker_volumes
      path: /var/lib/docker/volumes
