- name: "Configure the homeserver (type: Raspberry Pi 4)"
  hosts: rpi4

  roles:
    - role: nodejs
    - role: fstab
    - role: willshersystems.sshd
      become: true
      sshd:
        StreamLocalBindUnlink: true
