- name: "Configure the homeserver (type: Raspberry Pi 4)"
  hosts: rpi4

  roles:
    - role: fstab
    - role: willshersystems.sshd
      become: true
      sshd:
        StreamLocalBindUnlink: true
    - role: geerlingguy.docker
      become: true
      docker_install_compose_plugin: true
      docker_users:
        - "{{ ansible_user_id }}"
    - role: shell-environment
      prompt_device_id_var: "PROMPT_DEVICE_ID"
      prompt_device_id: "pi"

  tasks:
    # Clever solution found from:
    # https://serverfault.com/a/649355
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/default-packages.yml"

    - name: Install miscellaneous packages
      become: true
      package:
        name:
          - "{{ borgmatic_package }}"
          - "{{ lm_sensors_package }}"
        update_cache: true
        state: present
