- name: "Configure the homeserver (type: Raspberry Pi 4)"
  hosts: rpi4

  roles:
    - role: nodejs
    - role: fstab
    - role: willshersystems.sshd
      become: true
      sshd:
        StreamLocalBindUnlink: true
    - role: geerlingguy.docker
      become: true
      docker_install_compose_plugin: true
      docker_users:
        - "{{ ansible_user_id }}"
