# Installing and configuring oh-my-zsh
- src: gantsign.oh-my-zsh
  version: 2.7.0

# Docker
- src: geerlingguy.docker
  version: 4.2.4

# Configure the OpenSSH server daemon
- src: willshersystems.sshd
  version: v0.20.0
