galaxy_info:
  author: Valentin Furmanek
  description: Configure the fstab file

  license: MIT

  min_ansible_version: 2.1

  platforms:
  - name: Fedora
    versions:
    - all

  galaxy_tags: []

dependencies: []
