galaxy_info:
  author: Valentin Furmanek
  description: Install and configure Tmux

  license: MIT

  min_ansible_version: 2.1

  platforms:
  - name: Fedora
    versions:
    - all

  galaxy_tags: [tmux, environment]

dependencies: []
